apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "syspilot.name" . }}-collector
  labels:
    {{- include "syspilot.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "syspilot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: collector
