apiVersion: v1
kind: Service
metadata:
  name: {{ include "syspilot.name" . }}
  labels:
    {{- include "syspilot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "syspilot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: collector
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
