image:
  repository: ghcr.io/slumio/syspilot-cloud
  tag: "0.1.0"
  pullPolicy: IfNotPresent

serviceAccount:
  annotations: {}

secretName: syspilot-cloud-runtime

collector:
  replicas: 2
  databaseConnections: 32
  concurrentRequests: 512
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "2"
      memory: 1Gi
  autoscaling:
    minReplicas: 2
    maxReplicas: 20
    targetCPUUtilizationPercentage: 70

reasoning:
  replicas: 2
  endpoint: ""
  pollMilliseconds: 250
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: "1"
      memory: 512Mi

notification:
  replicas: 2
  endpoint: ""
  pollMilliseconds: 250
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: "1"
      memory: 512Mi

service:
  port: 80
