use crate::config;
use std::fs;
use std::time::{Duration, SystemTime};

const HEALTH_PATH: &str = "/tmp/syspilot-health.json";

const HOOK_CONTENT: &str = r#"# SysPilot hook — autogenerated by syspilot install
# Source this in your ~/.bashrc to enable logging:
#   source ~/.syspilot/syspilot.sh

if [ -n "$SYSPILOT_HOOK_LOADED" ]; then
    return
fi
export SYSPILOT_HOOK_LOADED=1

__syspilot_preexec() {
    echo "$(date +%s) $(pwd) $1" >> ~/.syspilot/command_start.log
}

__syspilot_precmd() {
    local exit_code=$?
    local last_cmd=$(history 1 | sed 's/^ *[0-9]* *//')
    echo "$(date -Iseconds) | $(pwd) | ${last_cmd} | ${exit_code}" >> ~/.syspilot/context.log
}

PROMPT_COMMAND="__syspilot_precmd; $PROMPT_COMMAND"
trap '__syspilot_preexec "$BASH_COMMAND"' DEBUG
"#;

pub fn install() -> bool {
    let dir = config::get_syspilot_dir();
    if let Err(e) = fs::create_dir_all(&dir) {
        eprintln!("❌ Could not create {}: {}", dir.display(), e);
        return false;
    }

    // Create log files if missing
    for name in &["session.log", "context.log", "command_start.log"] {
        let p = dir.join(name);
        if !p.exists() {
            let _ = fs::write(&p, "");
        }
    }

    // Create default config if missing
    let cfg_path = dir.join("config.json");
    if !cfg_path.exists() {
        let _ = config::save(&config::Config::default());
    }

    // Write the shell hook
    let hook_path = dir.join("syspilot.sh");
    if let Err(e) = fs::write(&hook_path, HOOK_CONTENT) {
        eprintln!(
            "❌ Failed to write hook script to {}: {}",
            hook_path.display(),
            e
        );
        return false;
    }

    println!("✅ SysPilot installed successfully.");
    println!("Hook script created at: {}", hook_path.display());
    println!("\nTo enable SysPilot, add this line to your ~/.bashrc:");
    println!("  source {}", hook_path.display());
    println!("\nThen restart your terminal or run: source ~/.bashrc");
    true
}

pub fn uninstall() -> bool {
    let dir = config::get_syspilot_dir();
    let hook_path = dir.join("syspilot.sh");
    if hook_path.exists() {
        let _ = fs::remove_file(&hook_path);
        println!("Removed hook script: {}", hook_path.display());
    }
    println!(
        "To completely remove SysPilot, delete the directory: {}",
        dir.display()
    );
    println!("Also remember to remove the 'source' line from your ~/.bashrc.");
    true
}

pub fn status() -> bool {
    let dir = config::get_syspilot_dir();
    let hook_path = dir.join("syspilot.sh");
    if hook_path.exists() {
        println!("✅ Hook script found: {}", hook_path.display());
        if std::env::var("SYSPILOT_HOOK_LOADED").is_ok() {
            println!("✅ Hook is active in this shell.");
        } else {
            println!("⚠️  Hook is not active in the current shell environment.");
            println!("Did you run `source ~/.syspilot/syspilot.sh` or add it to ~/.bashrc?");
        }
    } else {
        println!("❌ SysPilot is not installed. Run `syspilot install` first.");
    }
    match fs::metadata(HEALTH_PATH).and_then(|meta| meta.modified()) {
        Ok(modified) => match SystemTime::now().duration_since(modified) {
            Ok(age) if age <= Duration::from_secs(3) => {
                println!("✅ Daemon heartbeat is fresh ({} ms ago).", age.as_millis());
            }
            Ok(age) => println!(
                "❌ Daemon heartbeat is stale ({} seconds ago). Check systemd or restart the daemon.",
                age.as_secs()
            ),
            Err(_) => println!("⚠️  Daemon heartbeat timestamp is in the future."),
        },
        Err(_) => println!("❌ No daemon heartbeat found. Start `syspilot daemon &` or use systemd."),
    }
    true
}
